#!/usr/bin/env python3
"""Generate a bounded, dependency-free source and symbol index."""
import argparse
import ast
import os
from pathlib import Path
import re
import tempfile

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / 'docs/REPO_MAP.md'
TREES = ('apps', 'packages', 'tests', 'scripts', '.scripts', '.githooks', 'docs', '.github')
EXCLUDED_DIRS = set(
    '''
.git node_modules artifacts coverage reports .stryker-tmp dist build target
__pycache__ .pytest_cache .cache .npm-cache snapshots __snapshots__
'''.split()
)
EXTENSIONS = {
    '.py', '.js', '.jsx', '.ts', '.tsx', '.mjs', '.cjs', '.sh', '.md',
    '.html', '.css', '.json', '.yaml', '.yml', '.toml',
}
ROOT_FILES = {
    'AGENTS.md', 'README.md', 'Makefile', '.node-version', '.prettierrc.json', '.prettierignore',
    'eslint.config.mjs', 'package.json', 'tsconfig.ci.json',
    'vitest.ci.config.mjs', 'vitest.mutation.config.mjs', 'stryker.config.mjs',
}
MAX_BYTES = 256_000
MAX_SYMBOLS = 16
JS_DECL = re.compile(
    r'^\s*(?:export\s+)?(?:default\s+)?(?:declare\s+)?(?:async\s+)?'
    r'(?:function\s*\*?\s*|class\s+|interface\s+|type\s+|enum\s+)'
    r'([A-Za-z_$][\w$]*)'
)
JS_EXPORT = re.compile(r'^\s*export\s+(?:const|let|var)\s+([A-Za-z_$][\w$]*)')
JS_METHOD = re.compile(r'^\s*(?:async\s+)?([A-Za-z_$][\w$]*)\s*\([^;{}]*\)\s*\{')
JS_ARROW = re.compile(r'^\s*(?:const|let)\s+([A-Za-z_$][\w$]*)\s*=.*=>')


def allowed(path: Path) -> bool:
    relative = path.relative_to(ROOT)
    name = path.name
    return (
        not path.is_symlink()
        and not any(part in EXCLUDED_DIRS for part in relative.parts[:-1])
        and not name.startswith('.env')
        and 'lock' not in name.lower()
        and not any(part in name for part in ('.min.', '.bundle.', '.generated.', '.snap'))
        and path != OUTPUT
        and (name in ROOT_FILES or path.suffix in EXTENSIONS or '.githooks' in relative.parts)
    )


def candidates() -> list[Path]:
    paths = {path for path in ROOT.iterdir() if path.is_file() and allowed(path)}
    for tree in TREES:
        base = ROOT / tree
        if base.is_symlink() or not base.is_dir():
            continue
        for directory, directories, files in os.walk(base, followlinks=False):
            parent = Path(directory)
            directories[:] = sorted(
                directory_name
                for directory_name in directories
                if directory_name not in EXCLUDED_DIRS
                and not (parent / directory_name).is_symlink()
            )
            paths.update(parent / name for name in files if allowed(parent / name))
    def sort_key(path: Path) -> tuple[str, str]:
        relative = path.relative_to(ROOT)
        return ('' if len(relative.parts) == 1 else relative.parts[0], relative.as_posix())

    return sorted(paths, key=sort_key)


def symbols(path: Path, source: str) -> tuple[list[tuple[str, int]], str]:
    result: list[tuple[str, int]] = []
    if path.suffix == '.py':
        try:
            tree = ast.parse(source)
        except SyntaxError:
            return [], 'Python parse error; inspect source'
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                result.append((node.name, node.lineno))
                if isinstance(node, ast.ClassDef):
                    result.extend(
                        (f'{node.name}.{child.name}', child.lineno)
                        for child in node.body
                        if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef))
                    )
    elif path.suffix in {'.js', '.jsx', '.ts', '.tsx', '.mjs', '.cjs'}:
        for number, line in enumerate(source.splitlines(), 1):
            match = JS_DECL.match(line) or JS_EXPORT.match(line) or JS_ARROW.match(line) or JS_METHOD.match(line)
            if match and match[1] not in {'if', 'for', 'while', 'switch', 'catch', 'with'}:
                result.append((match[1], number))
    return list(dict.fromkeys(result)), ''


def render() -> str:
    lines = [
        '# Repository Map', '',
        'Generated by `.scripts/generate-repo-map.sh`; do not edit manually.', '',
        '## Navigation', '',
        '- `packages/construction/`: deterministic fill engine and worker protocol.',
        '- `packages/model-runtime/`: local model broker, adapters, and protocol.',
        '- `packages/generator/`: use cases and browser worker clients.',
        '- `apps/lab/`: private 15×15 Vite/React construction lab and local API.',
        '- `vendor/xfill/`: pinned MIT Rust fill engine and scored word list (not indexed).',
        '- `docs/`: integration and development documentation.',
        '- `.scripts/`: dependency-free repository-map tooling.',
        '- `.githooks/`: map-maintenance and freshness hooks.', '',
        '## Index contract', '',
        'Offline lightweight symbol dump: Python AST and a line-based JS/TS heuristic.',
        'Other files and tests are path-only. At most 16 symbols/file; `+N more` means search that file.',
        'Paths are deterministic and source bodies are never emitted. Dependency, VCS, generated,',
        'cache, report, fixture, snapshot, lockfile, and binary paths are excluded.',
        'Run `bash .scripts/generate-repo-map.sh --check` to detect drift without writing.', '',
    ]
    current = None
    for path in candidates():
        relative = path.relative_to(ROOT).as_posix()
        group = relative.split('/')[0] if '/' in relative else 'Root configuration & entry files'
        if group != current:
            lines.extend(['', f'## {group}', ''])
            current = group
        note = ''
        found: list[tuple[str, int]] = []
        is_test = path.name.startswith('test_') or any(part in path.name for part in ('.test.', '.spec.'))
        if path.stat().st_size > MAX_BYTES:
            note = 'large file; path only'
        elif not is_test and path.suffix in {'.py', '.js', '.jsx', '.ts', '.tsx', '.mjs', '.cjs'}:
            source = path.read_text(encoding='utf-8')
            if any(len(line) > 1000 for line in source.splitlines()):
                note = 'long-line source; path only'
            else:
                found, note = symbols(path, source)
        detail = ', '.join(f'`{name}:{line}`' for name, line in found[:MAX_SYMBOLS])
        if len(found) > MAX_SYMBOLS:
            detail += f' (+{len(found) - MAX_SYMBOLS} more)'
        if note:
            detail = note
        lines.append(f'- `{relative}`' + (f' — {detail}' if detail else ''))
    return '\n'.join(lines) + '\n'


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='exit 1 if the map is missing or stale')
    arguments = parser.parse_args()
    if OUTPUT.parent.is_symlink() or OUTPUT.is_symlink():
        parser.error('refusing symlinked output directory/file')
    content = render()
    if arguments.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != content:
            parser.exit(1, 'Repository map is missing or stale; run bash .scripts/generate-repo-map.sh\n')
        print('Repository map is current.')
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    temporary_name = None
    try:
        with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', dir=OUTPUT.parent, delete=False) as temporary:
            temporary_name = temporary.name
            temporary.write(content)
        os.chmod(temporary_name, 0o644)
        os.replace(temporary_name, OUTPUT)
    finally:
        if temporary_name and os.path.exists(temporary_name):
            os.unlink(temporary_name)
    print(f'Wrote docs/REPO_MAP.md ({len(content.encode("utf-8")):,} bytes).')


if __name__ == '__main__':
    main()
